name: break-a-scene
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp
  - accelerate
  - aiohttp
  - aiosignal
  - arrow-cpp
  - async-timeout
  - attrs
  - aws-c-common
  - aws-c-event-stream
  - aws-checksums
  - aws-sdk-cpp
  - blas
  - boost-cpp
  - bottleneck
  - brotli
  - brotli-bin
  - bzip2
  - c-ares
  - ca-certificates
  - cffi
  - click
  - colorama
  - dataclasses
  - datasets
  - dill
  - filelock
  - frozenlist
  - fsspec
  - future
  - gflags
  - glog
  - grpc-cpp
  - huggingface_hub
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - joblib
  - krb5
  - ld_impl_linux-64
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcurl
  - libedit
  - libev
  - libevent
  - libffi
  - libgcc-ng
  - libnghttp2
  - libprotobuf
  - libssh2
  - libthrift
  - libuuid
  - lz4-c
  - multidict
  - multiprocess
  - ncurses
  - ninja
  - ninja-base
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - orc
  - packaging
  - pandas
  - pip
  - protobuf
  - psutil
  - pyarrow
  - pycparser
  - pysocks
  - python
  - python-dateutil
  - python-xxhash
  - python_abi
  - pytorch
  - pytz
  - pyyaml
  - re2
  - readline
  - requests
  - sacremoses
  - setuptools
  - six
  - snappy
  - sqlite
  - tbb
  - tk
  - tokenizers
  - tqdm
  - transformers
  - typing-extensions
  - typing_extensions
  - tzdata
  - utf8proc
  - wheel
  - xxhash
  - xz
  - yaml
  - yarl
  - zipp
  - zlib
  - zstd
  - pip:
      - cchardet
      - certifi
      - chardet
      - charset-normalizer
      - diffusers
      - huggingface-hub
      - opencv-python
      - pillow
      - regex
      - urllib3
